### ISSUE TITLE
**Removal vs Put in Waiting Room:**

### ISSUE THREAD

**Issue by Crashsolver** [HamStudy/examtools-docs#29]
**Under Wrong Person admitted from the Waiting Room**

You write that removing someone from the meeting room with remove moves them back to waiting room. My experience in the past, and again today, while testing this, removed the person from the meeting. In the picture above the highlighted **remove** option is "Put in Waiting Room" why not use this instead?

![image](https://user-images.githubusercontent.com/72109174/107416891-017cab00-6ae3-11eb-8758-d72d89252e44.png)

**Update**, I was not using waiting room, hence the meeting removal. But removals do put you onto a bad boy list. if you do not follow the instruction to allow rejoining, they will not be allowed back. I have found that Zoom software updates resets switches. Just one more thing to worry about. The most recent update also reset the cohost switch, and my ability to share full screen as the host.

Thanks for all your great work

Dave N4NG

**Comment by nkbooth** [comment]
Yes, that is an unfortunate side effect of Zooms security "fun" - if you don't follow their security exactly, you get unintended results. More fun, as you discovered, Zoom "helpfully" resets your meeting security settings whenever they change anything about the security on their end.

**Comment by n2ygk** [comment]
Oops, my mistake.
