### ISSUE TITLE
Line 70, second sentence on cveCreateSession.md

### ISSUE THREAD

**Issue by TheButterZone** [HamStudy/examtools-docs#48]
https://github.com/hamstudy/examtools-docs/edit/master/content//docs/cve/cveCreateSession.md

(which has links to exam.tools & ham.study throughout, NOT sandbox)

> You may do this to proof-read it, **experiment** with formatting or share it with your VE team before it goes live using the private link.

(bolded for emphasis)

is contrary to ["Please use the sandbox for **all** training, demonstrations, or **experimentation** -- that's what it is there for."](https://discord.com/channels/695334374769557585/695335253023260672/857309107707314187)

If experiments/experimentation may _not_ be done on prod, **do not** say it _may_ be done on prod.

**Comment by nkbooth** [comment]
> Select the Schedule only and Do not list on HamStudy.org combo when you do not want the public to view it and register. You may do this to proof-read it, experiment with formatting or share it with your VE team before it goes live using the private link.

@TheButterZone think in context it's clear that the intent is to do editing on a session intended to be live, but if you have suggestions to make that more clear, I can work it in for sure. Maybe:

> Select the Schedule only and Do not list on HamStudy.org combo before you are ready for the public to view this session and register.

**Comment by TheButterZone** [comment]
Ok...

> Select the Schedule only and Do not list on HamStudy.org combo before you are ready for the public to view this session and register.

+

> You may do this to share it with your VE team before it goes live using the private link, however, please use the sandbox for all training, demonstrations, or experimentation -- that's what it is there for.
